# Guided local capability setup for opencode-remote.

[CmdletBinding()]
param(
    [switch]$CopyFallback,
    [switch]$SkipGithubToken
)

$ErrorActionPreference = "Stop"
$Repo = $PSScriptRoot
$EnvPath = Join-Path $Repo ".env"

function Get-DefaultHomeProjectRoot {
    foreach ($candidate in @("D:\Projects\_HomeProject", "D:\GitClone\_HomeProject")) {
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    return ""
}

function Read-RequiredValue {
    param(
        [string]$Prompt,
        [string]$DefaultValue
    )

    while ($true) {
        $suffix = if ([string]::IsNullOrWhiteSpace($DefaultValue)) { "" } else { " [$DefaultValue]" }
        $value = Read-Host "$Prompt$suffix"
        if ([string]::IsNullOrWhiteSpace($value)) {
            $value = $DefaultValue
        }

        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value.Trim()
        }

        Write-Host "Value is required." -ForegroundColor Yellow
    }
}

function Convert-SecureStringToPlainText {
    param([securestring]$SecureValue)

    $buffer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($buffer)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($buffer)
    }
}

function Get-EnvValue {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Name
    )

    $pattern = "^\s*$([regex]::Escape($Name))="
    foreach ($line in $Lines) {
        if ($line -match $pattern) {
            return $line -replace $pattern, ""
        }
    }

    return $null
}

function Set-EnvValue {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Name,
        [string]$Value
    )

    $pattern = "^\s*$([regex]::Escape($Name))="
    for ($i = 0; $i -lt $Lines.Count; $i++) {
        if ($Lines[$i] -match $pattern) {
            $Lines[$i] = "$Name=$Value"
            return
        }
    }

    $Lines.Add("$Name=$Value") | Out-Null
}

function Read-EnvLines {
    $lines = [System.Collections.Generic.List[string]]::new()
    if (Test-Path -LiteralPath $EnvPath) {
        Get-Content -LiteralPath $EnvPath | ForEach-Object { $lines.Add($_) | Out-Null }
    }
    else {
        $lines.Add("# Local opencode-remote settings. Generated by setup-capabilities.ps1.") | Out-Null
    }

    # Comma operator prevents PowerShell from unwrapping the List into Object[],
    # which would silently break Set-EnvValue's by-reference mutation.
    return , $lines
}

function Ensure-TargetAvailable {
    param(
        [string]$Path,
        [string]$Source
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return $true
    }

    $item = Get-Item -LiteralPath $Path -Force
    $targets = @()
    if ($null -ne $item.Target) {
        $targets = @($item.Target) | ForEach-Object { $_.ToString() }
    }
    if ($item.LinkType -and ($targets -contains $Source)) {
        Write-Host "Already wired: $Path" -ForegroundColor Green
        return $false
    }

    Write-Host "Target already exists and is not managed by this setup: $Path" -ForegroundColor Yellow
    $choice = Read-Host "Type REPLACE to replace this one path, or press Enter to stop"
    if ($choice -ne "REPLACE") {
        throw "Stopped before replacing existing path: $Path"
    }

    Remove-Item -LiteralPath $Path -Recurse -Force
    return $true
}

function Copy-CapabilityFiles {
    param([string]$HomeProjectRoot)

    $mode = "copy fallback"
    $configTarget = Join-Path $HomeProjectRoot "opencode.json"
    $agentsFileTarget = Join-Path $HomeProjectRoot "AGENTS.md"
    $agentsDirTarget = Join-Path $HomeProjectRoot ".opencode\agents"

    if (Ensure-TargetAvailable $configTarget (Join-Path $Repo "opencode.json")) {
        Copy-Item -LiteralPath (Join-Path $Repo "opencode.json") -Destination $configTarget
    }
    if (Ensure-TargetAvailable $agentsFileTarget (Join-Path $Repo "AGENTS.md")) {
        Copy-Item -LiteralPath (Join-Path $Repo "AGENTS.md") -Destination $agentsFileTarget
    }
    if (Ensure-TargetAvailable $agentsDirTarget (Join-Path $Repo ".opencode\agents")) {
        New-Item -ItemType Directory -Force -Path $agentsDirTarget | Out-Null
        Copy-Item -Path (Join-Path $Repo ".opencode\agents\*.md") -Destination $agentsDirTarget -Force
    }

    return $mode
}

function Link-CapabilityFiles {
    param([string]$HomeProjectRoot)

    $mode = "symlink/junction"
    $configTarget = Join-Path $HomeProjectRoot "opencode.json"
    $agentsFileTarget = Join-Path $HomeProjectRoot "AGENTS.md"
    $opencodeDir = Join-Path $HomeProjectRoot ".opencode"
    $agentsDirTarget = Join-Path $opencodeDir "agents"

    if (Ensure-TargetAvailable $configTarget (Join-Path $Repo "opencode.json")) {
        New-Item -ItemType SymbolicLink -Path $configTarget -Target (Join-Path $Repo "opencode.json") | Out-Null
    }
    if (Ensure-TargetAvailable $agentsFileTarget (Join-Path $Repo "AGENTS.md")) {
        New-Item -ItemType SymbolicLink -Path $agentsFileTarget -Target (Join-Path $Repo "AGENTS.md") | Out-Null
    }

    New-Item -ItemType Directory -Force -Path $opencodeDir | Out-Null
    if (Ensure-TargetAvailable $agentsDirTarget (Join-Path $Repo ".opencode\agents")) {
        New-Item -ItemType Junction -Path $agentsDirTarget -Target (Join-Path $Repo ".opencode\agents") | Out-Null
    }

    return $mode
}

$envLines = Read-EnvLines
$homeProjectRoot = Get-EnvValue $envLines "OPENCODE_DIRECTORY"
if ([string]::IsNullOrWhiteSpace($homeProjectRoot) -or -not (Test-Path -LiteralPath $homeProjectRoot)) {
    $defaultRoot = Get-DefaultHomeProjectRoot
    do {
        $homeProjectRoot = Read-RequiredValue "OPENCODE_DIRECTORY" $defaultRoot
        if (-not (Test-Path -LiteralPath $homeProjectRoot)) {
            Write-Host "Path does not exist: $homeProjectRoot" -ForegroundColor Yellow
        }
    } while (-not (Test-Path -LiteralPath $homeProjectRoot))
}

# Normalize to forward slashes so opencode.json env interpolation produces valid JSON.
# Backslashes in the value would land inside JSON strings as invalid escape sequences
# (e.g. \G, \_) when opencode.json substitutes {env:OPENCODE_DIRECTORY}.
$homeProjectRoot = $homeProjectRoot.TrimEnd('\', '/') -replace '\\', '/'

Set-EnvValue $envLines "OPENCODE_DIRECTORY" $homeProjectRoot

if ([string]::IsNullOrWhiteSpace((Get-EnvValue $envLines "PORT"))) {
    Set-EnvValue $envLines "PORT" "9223"
}
if ([string]::IsNullOrWhiteSpace((Get-EnvValue $envLines "OPENCODE_PORT"))) {
    Set-EnvValue $envLines "OPENCODE_PORT" "4096"
}
if ([string]::IsNullOrWhiteSpace((Get-EnvValue $envLines "SESSION_REFRESH_INTERVAL_MS"))) {
    Set-EnvValue $envLines "SESSION_REFRESH_INTERVAL_MS" "30000"
}

if (-not $SkipGithubToken) {
    $githubToken = Get-EnvValue $envLines "GITHUB_TOKEN"
    if ([string]::IsNullOrWhiteSpace($githubToken)) {
        $secureToken = Read-Host "Optional GitHub token for GitHub MCP (leave blank to skip)" -AsSecureString
        if ($secureToken.Length -gt 0) {
            Set-EnvValue $envLines "GITHUB_TOKEN" (Convert-SecureStringToPlainText $secureToken)
        }
        elseif ($null -eq $githubToken) {
            Set-EnvValue $envLines "GITHUB_TOKEN" ""
        }
    }
}

# Write UTF-8 WITHOUT BOM. Windows PowerShell 5.1's `-Encoding UTF8` writes a
# BOM, which breaks Node's `--env-file` parser on the first variable
# (variable looks unset even though the file is readable).
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($EnvPath, ($envLines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
Write-Host "Wrote local .env without printing secret values." -ForegroundColor Green

if ($CopyFallback) {
    $setupMode = Copy-CapabilityFiles $homeProjectRoot
}
else {
    try {
        $setupMode = Link-CapabilityFiles $homeProjectRoot
    }
    catch {
        Write-Host "Symlink/junction setup failed: $($_.Exception.Message)" -ForegroundColor Yellow
        $answer = Read-Host "Use copy fallback instead? [Y/n]"
        if ($answer -match "^(n|no)$") {
            throw
        }
        $setupMode = Copy-CapabilityFiles $homeProjectRoot
    }
}

Write-Host "Capability setup complete." -ForegroundColor Green
Write-Host "Runtime root: $homeProjectRoot" -ForegroundColor Cyan
Write-Host "Setup mode: $setupMode" -ForegroundColor Cyan
Write-Host "Next: .\restart-service.ps1" -ForegroundColor Cyan
